pages: # the job must be named pages
  image: node:22
  stage: deploy
  variables:
    CI_PROJECT_NAME: "my-vuejs-project"
  script:
    - yarn install
    - yarn run build
    - cp dist/index.html dist/404.html
    - mv public public-vue # GitLab Pages hooks on the public folder
    - mv dist public # rename the dist folder (result of npm run build)
    # optionally, you can activate gzip support wih the following line:
    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec gzip -f -k {} \;
  artifacts:
    paths:
      - public # artifact path must be /public for GitLab Pages to pick it up
  only:
    - main